apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: helloworld-deployments
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
