apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
  - name: helloworld 
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: LoadBalancer
